### ISSUE TITLE
Port 80 switch

### ISSUE THREAD

**Issue by cataclysmic** [tobiasraabe/otree_virtual_machine_manager#86]
On ovvm initialise:

- [ ] create folder query whether port change should be doable by user - default admin
- [ ] create folder "/var/port_80_switch
- [ ] set permissions according to 1 - group permissions writeable group either *admin* or *users*
- [ ] copy default nginx config to /etc/nginx/sites-available that calls /var/port_80_switch/otree
- [ ] write user command to switch port (not in static package) 
- [ ] make available to admin ?~/local/bin
- [ ] copy to users' ~/local/bin is users are allowed to use

Felix: provides switch command and default nginx

**Propose functionality:**

*** TODO nginx default config setup [0%]

- [ ] nginx default config - bot block
- [ ] replace original setup default config with ours

*** TODO Make default port switchable [0%]

**** TODO decide whether only admin  or user can switch ports

**** TODO if users are allowed

- [ ] create linux usergroup *otree* on initialise
- [ ] config folder creating with otree group permission
- [ ] assign newly created users to group *otree*
- [ ] create symlink *otree_link* in folder
- [ ] shell script that deletes symlink *otree_link* and creates new one to HOME/.oTree

**** TODO if only admin

- [ ] ovmm query for username to switch default port to
- [ ] delete current *otree_link* replace with symlink to /home/username/.oTree
